/*
 * ConfigForm.java
 *
 * Created on February 23, 2005, 8:53 PM
 */

import javax.swing.*;
import javax.swing.filechooser.*;
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
public class ConfigForm extends JFrame {
    //Vector params;
    //JFileChooser fileDialog;
    CommModule c ;
    MainWindow  appWindow;
    int numNodes = 8;
    JPanel jpLoad;
    JPanel jpStart;
    JPanel jpCurrent;
    /** Creates new form ConfigForm */
    public ConfigForm() {
        jpStart = new ConfigFormPane1(this);
        
        showStart();
        initComponents();
    }
    
    public void setNumNodes(int n){
           numNodes = n;
    }
    
    public void showStart(){
        jpCurrent = jpStart;
        getContentPane().add(jpCurrent);
        pack();
    }
    public void showLoadClass(File file){
        getContentPane().remove(jpCurrent);
        jpLoad = new ConfigFormLoadClass(this,file);
        jpCurrent = jpLoad;
        getContentPane().add(jpCurrent);
        pack();
    }
    
    public void start(ClassDetails[][] selectedClasses){ 
  
        CommModule c = new CommModule();
        c.init(numNodes, selectedClasses);
        appWindow =  new MainWindow(c);
        c.setAppWindow(appWindow);
        appWindow.show();
        getContentPane().remove(jpCurrent);
        jpCurrent = jpStart;
        getContentPane().add(jpStart);
        pack();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulation Wizard");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("Simulation Wizard");
        setResizable(false);
        jLabel4.setText("    ");
        getContentPane().add(jLabel4);

        getContentPane().add(jPanel1);

        pack();
    }//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
